---
apiVersion: v1
kind: Service
metadata:
  name: technitium-dns-service
  namespace: technitium-dns
  labels:
    app.kubernetes.io/instance: technitium-dns
spec:
  selector:
    app: technitium-dns
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5380
      targetPort: http-console
      name: http-console
    - protocol: TCP
      port: 53443
      targetPort: https-console
      name: https-console
    - protocol: TCP
      port: 53
      targetPort: dns-tcp
      name: dns-tcp
    - protocol: UDP
      port: 53
      targetPort: dns-udp
      name: dns-udp
