---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nextcloud
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  storageClassName: rook-cephfs-ci
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
