---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vpa-lightspeed-app-server.yaml
  - vpa-lightspeed-console-plugin.yaml
  - vpa-lightspeed-otel-collector.yaml
  - vpa-lightspeed-operator-controller-manager.yaml
  - vpa-lightspeed-postgres-server.yaml
  - vpa-lightspeed-rhokp.yaml
  - vpa-openshift-mcp-server.yaml
