---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lightspeed-postgres-server
  namespace: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: lightspeed-postgres-server
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lightspeed-postgres-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: lightspeed-postgres-server
        minAllowed:
          cpu: 10m
          memory: 100Mi
        maxAllowed:
          cpu: 1
          memory: 2Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
