---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lightspeed-otel-collector
  namespace: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: lightspeed-otel-collector
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lightspeed-otel-collector
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: collector
        minAllowed:
          cpu: 10m
          memory: 32Mi
        maxAllowed:
          cpu: "1"
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
