---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lightspeed-app-server
  namespace: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: lightspeed-app-server
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lightspeed-app-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: lightspeed-service-api
        minAllowed:
          cpu: 50m
          memory: 128Mi
        maxAllowed:
          cpu: "2"
          memory: 4Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
      - containerName: lightspeed-to-dataverse-exporter
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 500m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
