---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microshift
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: microshift
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
        annotations:
          managed-by: argocd.argoproj.io
      data:
        name: microshift
        server: https://microshift.arthurvardevanyan.com:6443
        caData: "{{ .ca }}"
  data:
    - secretKey: ca
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: microshift
        property: ca
        metadataPolicy: None
