---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: open-webui-cnpg
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/instance: open-webui
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: open-webui
  podMetricsEndpoints:
    - port: metrics
