---
apiVersion: hco.kubevirt.io/v1
kind: HyperConverged
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
    deployOVS: "false"
  name: kubevirt-hyperconverged
  namespace: kubevirt-hyperconverged
  labels:
    app: kubevirt-hyperconverged
    argocd.argoproj.io/instance: kubevirt
spec:
  deployment:
    nodePlacements:
      workload:
        tolerations:
          - key: node-role.kubernetes.io/gpu
            operator: Exists
            effect: NoSchedule
    uninstallStrategy: BlockUninstallIfWorkloadsExist
  featureGates:
    - name: decentralizedLiveMigration
      state: Enabled
    - name: downwardMetrics
      state: Disabled
    - name: disableMDevConfiguration
      state: Disabled
    - name: deployKubeSecondaryDNS
      state: Disabled
    - name: alignCPUs
      state: Disabled
    - name: persistentReservation
      state: Disabled
    - name: autoResourceLimits
      state: Disabled
  security:
    certConfig:
      ca:
        duration: 48h0m0s
        renewBefore: 24h0m0s
      server:
        duration: 24h0m0s
        renewBefore: 12h0m0s
  storage:
    scratchSpaceStorageClass: rook-ceph-block-virtualization-ci
    workloadResourceRequirements:
      limits:
        cpu: 750m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 500m
  virtualization:
    evictionStrategy: LiveMigrate
    higherWorkloadDensity:
      memoryOvercommitPercentage: 100
    liveMigrationConfig:
      allowAutoConverge: false
      allowPostCopy: false
      bandwidthPerMigration: 2Gi
      completionTimeoutPerGiB: 800
      network: live-migrate
      parallelMigrationsPerCluster: 5
      parallelOutboundMigrationsPerNode: 2
      progressTimeout: 150
    virtualMachineOptions:
      disableFreePageReporting: false
      disableSerialConsoleLog: true
    vmiCPUAllocationRatio: 10
    workloadUpdateStrategy:
      batchEvictionInterval: 1m0s
      batchEvictionSize: 10
      workloadUpdateMethods:
        - LiveMigrate
  workloadSources:
    enableCommonBootImageImport: true
