---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui-cert
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    app.kubernetes.io/instance: open-webui
spec:
  secretName: open-webui-cert
  duration: 1080h # 45d
  renewBeforePercentage: 50
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256 # P-384 not supported by Envoy/OpenShift Ingress for re-encrypt (wrong_curve)
  dnsNames:
    - "ai.arthurvardevanyan.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
