apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: stackrox
  namespace: stackrox
spec:
  schedule: "0 15 3 * * *"
  backupOwnerReference: self
  cluster:
    name: stackrox
  method: volumeSnapshot
