---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/gateway/internal
  - ../../components/gateway/external
  - ../../components/coraza/rules
  - ../../components/coraza/engine/internal
  - ../../components/coraza/engine/external
  - ../../components/wiretap/configs/v0.0.0+/internal
  - ../../components/wiretap/configs/v0.0.0+/internet
  - ../../components/wiretap/instance/v0.0.0
  - ../../components/wiretap/victoria-metrics
