---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sable-dns-data
  namespace: sable-dns
  labels:
    app.kubernetes.io/instance: sable-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
