---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quay-app
  namespace: quay
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: quay
      quay-component: quay-app
      quay-operator/quayregistry: quay
