---
- name: Install Hashicorp Tools
  hosts: lenovo
  gather_facts: false
  become: true
  user: arthur
  tasks:
    - name: Download Vault zip
      ansible.builtin.get_url:
        # renovate: datasource=github-releases depName=hashicorp/vault
        url: https://releases.hashicorp.com/vault/1.21.4/vault_1.21.4_linux_arm64.zip
        dest: /tmp/vault.zip
        timeout: 120
        mode: "0644"
    - name: Install Vault
      ansible.builtin.unarchive:
        src: /tmp/vault.zip
        dest: /usr/local/bin
        mode: "0755"
