---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cluster-logging-operator
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-logging-operator
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: cluster-logging-operator
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 50m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-distributor
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logging-loki-distributor
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: loki-distributor
        minAllowed:
          cpu: 5m
          memory: 32Mi
        maxAllowed:
          cpu: 200m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-gateway
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logging-loki-gateway
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: gateway
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 100m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
      - containerName: opa
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 100m
          memory: 128Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-querier
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logging-loki-querier
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: loki-querier
        minAllowed:
          cpu: 5m
          memory: 32Mi
        maxAllowed:
          cpu: 200m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-query-frontend
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logging-loki-query-frontend
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: loki-query-frontend
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 150m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-compactor
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logging-loki-compactor
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: loki-compactor
        minAllowed:
          cpu: 5m
          memory: 32Mi
        maxAllowed:
          cpu: 200m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-index-gateway
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logging-loki-index-gateway
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: loki-index-gateway
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 150m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logging-loki-ingester
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: logging-loki-ingester
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: loki-ingester
        minAllowed:
          cpu: 5m
          memory: 32Mi
        maxAllowed:
          cpu: 500m
          memory: 6Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: collector
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: collector
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: collector
        minAllowed:
          cpu: 10m
          memory: 32Mi
        maxAllowed:
          cpu: 300m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: logfilesmetricexporter
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: logfilesmetricexporter
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: logfilesmetricexporter
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 200m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
