---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: quay-dragonfly
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 2
  skipFSGroup: true
  # renovate: datasource=docker depName=docker.dragonflydb.io/dragonflydb/dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.0@sha256:84b1009aee0b68327758bce8e99ed514f782d713353acc46caf5738feaa481d6
  resources:
    limits:
      cpu: 75m
      memory: 320Mi
    requests:
      cpu: 25m
      memory: 64Mi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: dragonfly
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
  # snapshot:
  #   cron: "*/5 * * * *"
  #   persistentVolumeClaimSpec:
  #     storageClassName: rook-ceph-block

  #     accessModes:
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 1Gi
