---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-env
  namespace: renovate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: renovate-env
    # creationPolicy: "Merge"
  data:
    #  https://api.github.com/users/homelab-okd[bot]
    - secretKey: GITHUB_APP_ID
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/tekton
        property: github_app
        metadataPolicy: None
    - secretKey: GITHUB_APP_INSTALLATION_ID
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/tekton
        property: github_app_installation
        metadataPolicy: None
    - secretKey: GITHUB_APP_KEY
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/tekton
        property: github_pk
        metadataPolicy: None
