---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ipAddressPools:
    - metallb-pool
  aggregationLength: 32
  localPref: 100
  communities:
    - 65535:65282
