router bgp 65000
  bgp router-id 10.101.10.1

  ! Define the peer group for k8s nodes (iBGP)
  neighbor K8S-NODES peer-group
  neighbor K8S-NODES remote-as 65000
  neighbor K8S-NODES soft-reconfiguration inbound
  neighbor K8S-NODES next-hop-self

  ! Assign nodes to the group
  neighbor 10.101.10.101 peer-group K8S-NODES
  neighbor 10.101.10.102 peer-group K8S-NODES
  neighbor 10.101.10.103 peer-group K8S-NODES
  neighbor 10.101.10.104 peer-group K8S-NODES
  neighbor 10.101.10.105 peer-group K8S-NODES
  neighbor 10.101.10.106 peer-group K8S-NODES
  neighbor 10.101.10.107 peer-group K8S-NODES

address-family ipv4 unicast
  neighbor K8S-NODES activate
  neighbor K8S-NODES route-map ALLOW-METALLB-LB in
  neighbor K8S-NODES prefix-list METALLB-POOL in
exit-address-family

!
ip prefix-list METALLB-POOL seq 10 permit 10.101.10.240/28 le 32
!
route-map ALLOW-METALLB-LB permit 10
  match ip address prefix-list METALLB-POOL
!
