---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bmc-shim
  namespace: bmc-shim
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: bmc-shim
