---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: istiod-openshift-gateway
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  background: false
  rules:
    - name: istiod-openshift-gateway
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - HorizontalPodAutoscaler
              names:
                - istiod-openshift-gateway
      mutate:
        patchStrategicMerge:
          spec:
            minReplicas: 2
    - name: gateway-resources
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Deployment
              names:
                - https-gateway-openshift-default
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                containers:
                  - (name): istio-proxy
                    resources:
                      requests:
                        cpu: 150m
                        memory: 512Mi
                      limits:
                        cpu: 450m
                        memory: 1536Gi
