---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - network-policy.yaml
  - service-monitor.yaml
  - vpa.yaml

configMapGenerator:
  - files:
      - llama-swap.yaml
    name: llama-swap-config
    namespace: llm
