---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: llm-llama-swap-store
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block-ci
  volumeMode: Filesystem
