---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-vllm-cache
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block-ci
  volumeMode: Filesystem
