---
apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: openshift-frr-k8s
  labels:
    app.kubernetes.io/instance: metallb
spec:
  limits:
    - type: Container
      default:
        cpu: 30m
        memory: 64Mi
      defaultRequest:
        cpu: 10m
        memory: 32Mi
