---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - vpa.yaml
  - network-policy.yaml
  - secret.yaml

configMapGenerator:
  - files:
      - litellm.yaml
      - llama_swap_affinity.py
    name: litellm-config
    namespace: llm
