---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: llm-litellm-state
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block-ci
  volumeMode: Filesystem
