---
model_list:
  # --- Public Model Alias 1: Qwen 35B (30 t/s avg decode, ~593W system w/ HVAC) ---
  - model_name: qwen3.6-35b-a3b
    litellm_params:
      model: openai/35b-gpu0
      api_base: http://llama-swap-svc.llm.svc.cluster.local:8080/v1
      api_key: "dummy"
      input_cost_per_token: 0.00000186
      output_cost_per_token: 0.00000124
  - model_name: qwen3.6-35b-a3b
    litellm_params:
      model: openai/35b-gpu1
      api_base: http://llama-swap-svc.llm.svc.cluster.local:8080/v1
      api_key: "dummy"
      input_cost_per_token: 0.00000186
      output_cost_per_token: 0.00000124

  # --- Public Model Alias 2: Qwen 27B (~14 t/s avg decode, ~593W system w/ HVAC) ---
  - model_name: qwen3.6-27b
    litellm_params:
      model: openai/27b-gpu0
      api_base: http://llama-swap-svc.llm.svc.cluster.local:8080/v1
      api_key: "dummy"
      input_cost_per_token: 0.00000398
      output_cost_per_token: 0.00000265
  - model_name: qwen3.6-27b
    litellm_params:
      model: openai/27b-gpu1
      api_base: http://llama-swap-svc.llm.svc.cluster.local:8080/v1
      api_key: "dummy"
      input_cost_per_token: 0.00000398
      output_cost_per_token: 0.00000265

  # --- Public Model Alias 3: Qwen Coder 30B (~13 t/s avg decode, ~593W system w/ HVAC) ---
  - model_name: qwen3.6-coder-30b-a3b
    litellm_params:
      model: openai/coder30b-gpu0
      api_base: http://llama-swap-svc.llm.svc.cluster.local:8080/v1
      api_key: "dummy"
      input_cost_per_token: 0.00000431
      output_cost_per_token: 0.00000287
  - model_name: qwen3.6-coder-30b-a3b
    litellm_params:
      model: openai/coder30b-gpu1
      api_base: http://llama-swap-svc.llm.svc.cluster.local:8080/v1
      api_key: "dummy"
      input_cost_per_token: 0.00000431
      output_cost_per_token: 0.00000287

general_settings:
  health_check_interval: 300
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Email
      litellm_user_role: customer

router_settings:
  routing_strategy: least-busy

litellm_settings:
  callbacks:
    - prometheus
  require_auth_for_metrics_endpoint: false
