---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-config
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: litellm-config
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/litellm
        property: master_key
        metadataPolicy: None
    - secretKey: UI_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/litellm
        property: ui_username
        metadataPolicy: None
    - secretKey: UI_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/litellm
        property: ui_password
        metadataPolicy: None
