---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: litellm
spec:
  enablePDB: false
  imageName: "ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie@sha256:006b7801eacd9706d6fb557520a414a7d938e4e71333da98695f6f03b20e4cee"
  instances: 1
  imagePullPolicy: IfNotPresent
  logLevel: info
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  startDelay: 3600
  stopDelay: 1800
  smartShutdownTimeout: 180
  postgresUID: 26
  postgresGID: 26
  affinity:
    nodeSelector:
      node-role.kubernetes.io/gpu: ""
    tolerations:
      - key: node-role.kubernetes.io/gpu
        operator: Exists
        effect: NoSchedule
  postgresql:
    parameters:
      shared_buffers: "128MB"
      wal_keep_size: "2GB"
    pg_hba:
      - "host all all 10.101.32.0/19 md5"
  bootstrap:
    initdb:
      database: litellm
      owner: postgres
  enableSuperuserAccess: true
  monitoring:
    enablePodMonitor: false
  storage:
    storageClass: rook-ceph-block
    size: 4Gi
  walStorage:
    storageClass: rook-ceph-block
    size: 5Gi
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 1Gi
  seccompProfile:
    type: RuntimeDefault
  backup:
    volumeSnapshot:
      className: csi-rbdplugin-snapclass
