---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nextcloud-cnpg
  namespace: nextcloud-fpm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/instance: nextcloud-fpm
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: nextcloud
  podMetricsEndpoints:
    - port: metrics
