---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: metallb-operator-controller-manager
  annotations:
    checkov.io/skip1: CKV_K8S_40=OpenShift Injects Random UID
  namespace: metallb-system
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --enable-leader-election
          command:
            - /manager
          env:
            - name: DEPLOY_SERVICEMONITORS
              value: "true"
            - name: METALLB_BGP_TYPE
              value: frr
            - name: SPEAKER_IMAGE
              value: quay.io/metallb/speaker@sha256:b09a1dfcf330938950b65115cd58f6989108c0c21d3c096040e7fe9a25a92993 # v0.14.9
            - name: CONTROLLER_IMAGE
              value: quay.io/metallb/controller@sha256:86261567e5ff03978893bf03ea865275283ad1e3f0f20dd342ed501b651fdf78 # v0.14.9
            - name: FRR_IMAGE
              value: quay.io/frrouting/frr@sha256:848482643a8d6f56452b659ea68f6138472bb57414a4f295a7c4107a0416269c # 10.5.1
            - name: KUBE_RBAC_PROXY_IMAGE
              value: quay.io/brancz/kube-rbac-proxy:v0.11.0
            - name: DEPLOY_KUBE_RBAC_PROXIES
              value: "false"
            - name: FRRK8S_IMAGE
              value: quay.io/metallb/frr-k8s@sha256:ee5dcdeb9520c78066e8af4a47de1c05d2b36db442034b02b1210e3d7fd17e45 # v0.0.22
            - name: FRRK8S_EXTERNAL_NAMESPACE
              value: frr-k8s-system
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/metallb/metallb-operator:0.14.2@sha256:df5a10332e70b47ada287b39b4b7fb6b5b4aac048347b938b490645e14d351f0
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            requests:
              ephemeral-storage: "100Mi"
              memory: "48Mi"
              cpu: "5m"
            limits:
              ephemeral-storage: "200Mi"
              memory: "256Mi"
              cpu: "100m"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      serviceAccountName: manager-account
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: metallb-operator-webhook-server-cert
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  control-plane: controller-manager
              topologyKey: "kubernetes.io/hostname"
      enableServiceLinks: false
