---
apiVersion: v1
kind: Service
metadata:
  name: metallb-operator-webhook-service
  namespace: metallb-system
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: webhook-server
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: metallb-system
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: webhook-server
  selector:
    component: webhook-server
