apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/engines.yaml
  - ./crds/rulesets.yaml
  - ./rbac/clusterrole.yaml
  - ./rbac/clusterrolebinding.yaml
  - ./rbac/serviceaccount.yaml
  - ./istio/serviceentry.yaml
  - ./istio/destinationrule.yaml
  - ./servicemonitor.yaml
  - ./namespace.yaml
  # - ./pdb.yaml # HA Doesn't Work ATM
  - ./service.yaml
  - ./deployment.yaml
