---
# Source: coraza-kubernetes-operator/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: coraza-system
  labels:
    helm.sh/chart: coraza-kubernetes-operator-0.1.0
    app.kubernetes.io/name: coraza-kubernetes-operator
    app.kubernetes.io/instance: coraza-kubernetes-operator
    control-plane: coraza-controller-manager
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
