---
# Source: coraza-kubernetes-operator/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coraza-kubernetes-operator
  namespace: coraza-system
  labels:
    helm.sh/chart: coraza-kubernetes-operator-0.1.0
    app.kubernetes.io/name: coraza-kubernetes-operator
    app.kubernetes.io/instance: coraza-kubernetes-operator
    control-plane: coraza-controller-manager
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coraza-kubernetes-operator
      app.kubernetes.io/instance: coraza-kubernetes-operator
      control-plane: coraza-controller-manager
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
