---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: sable-dns-cert
  namespace: sable-dns
spec:
  secretName: sable-dns-cert
  duration: 1080h # 45d
  renewBeforePercentage: 50
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256 # P-384 not supported by Envoy/OpenShift Ingress for re-encrypt (wrong_curve)
  keystores:
    pkcs12:
      create: true
      password: sable-dns
      profile: Modern2023
  dnsNames:
    - "sabledns.io"
    - "dns.sabledns.io"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
