---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    operatorframework.io/bundle-unpack-min-retry-interval: 30m
  labels:
    app.kubernetes.io/instance: argocd
  name: argocd-operator
  namespace: argocd-operator
