---
apiVersion: pipelines.openshift.io/v1alpha1
kind: GitopsService
metadata:
  name: cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  consolePlugin:
    backend:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: "500m"
          memory: 256Mi
    gitopsPlugin:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: "500m"
          memory: 256Mi
