---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - installplan-approver.yaml
  - operator-vpa.yaml
  - egress-firewall.yaml
  - network-policy.yaml
