---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitea-backup
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/instance: gitea
spec:
  schedule: "0 45 3 * * *"
  backupOwnerReference: self
  method: volumeSnapshot
  cluster:
    name: gitea
