---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pr-agent-dragonfly
  namespace: pr-agent
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: pr-agent-dragonfly
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pr-agent-dragonfly
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: dragonfly
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: "1"
          memory: 2Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
