---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  # - heimdall.yaml
  # - kubernetes-dashboard.yaml
  # - longhorn.yaml
  # - stackrox-secure.yaml
  # - traefik.yaml
  # - vault.yaml
