---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - installplan-approver.yaml
  - gpu-device-plugin.yaml
  - xpumd/scc.yaml
  - xpumd/configmap.yaml
  - xpumd/service-account.yaml
  - xpumd/service.yaml
  - xpumd/service-monitor.yaml
  - xpumd/daemonset.yaml
  - gpu-power-manager.yaml
