---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: intel-device-plugins-operator
  namespace: intel-device-plugins-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: intel-device-plugins-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: intel-device-plugins-operator.v0.36.0
  config:
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: 50m
