---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - gitopsservice.yaml
  - hpa.yaml
  - namespace.yaml
  - pdb.yaml
  - vpa.yaml
  - egress-firewall.yaml
  - network-policy.yaml
