---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: cluster
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: "1"
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gitops-plugin
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gitops-plugin
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: gitops-plugin
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: "1"
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
