---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-llm-embed-ingress-from-open-webui
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: llm-embed
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: llm-embed
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: llm
          podSelector:
            matchLabels:
              app.kubernetes.io/name: open-webui
      ports:
        - protocol: TCP
          port: 11435
    - from:
        - podSelector:
            matchLabels:
              app: litellm
      ports:
        - protocol: TCP
          port: 11435
