---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: llm-embed
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: llm-embed
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-embed
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: llm-embed
        minAllowed:
          cpu: 100m
          memory: 256Mi
          ephemeral-storage: 64Mi
        maxAllowed:
          cpu: "3"
          memory: 24Gi
          ephemeral-storage: 512Mi
        controlledResources:
          - cpu
          - memory
          - ephemeral-storage
        controlledValues: RequestsOnly
