---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/instance: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
