---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microshift-ca
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: microshift-ca
  data:
    - secretKey: caData
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: microshift
        property: ca
        metadataPolicy: None
