apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: grafana
  method: volumeSnapshot
