FROM registry.access.redhat.com/ubi9-minimal:latest

COPY ./containers/toolbox/repos /etc/yum.repos.d/

RUN microdnf install --nodocs -y --disableplugin=subscription-manager \
  sshpass logrotate rsync git jq unzip MariaDB-client ansible google-cloud-cli tar -y  \
  && rm -rf /var/cache/* /var/lib/rpm/* && \
  rm -rf /usr/lib64/google-cloud-sdk/{platform,data,bin/anthoscli}

ENV \
  ARGOCD_VAULT_VERSION=1.16.1 \
  OKD_VERSION=4.13.0-0.okd-2023-09-30-084937 \
  VAULT_VERSION=1.15.0 \
  HOME=/tmp \
  KICK="0"

RUN curl -L -o argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${ARGOCD_VAULT_VERSION}/argocd-vault-plugin_${ARGOCD_VAULT_VERSION}_linux_amd64 && \
  chmod +x argocd-vault-plugin && mv argocd-vault-plugin /usr/local/bin \
  && \
  curl -L -o yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64  && \
  chmod +x yq && mv yq /usr/local/bin \
  && \
  curl -L -o openshift-client-linux.tar.gz https://github.com/openshift/okd/releases/download/${OKD_VERSION}/openshift-client-linux-${OKD_VERSION}.tar.gz && \
  tar -xzf openshift-client-linux.tar.gz && mv oc /usr/local/bin/kubectl && rm -f oc kubectl openshift-client-linux.tar.gz\\
  && \
  curl -L -o vault_linux_amd64.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip && \
  unzip vault_linux_amd64.zip && chmod +x vault && mv vault /usr/local/bin/

CMD ["sleep", "infinity"]
