---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/openshift
patches:
  - patch: |-
      - op: replace
        path: /spec/instances
        value: 1
      - op: replace
        path: /spec/storage/storageClass
        value: lvms-vg1-immediate
      - op: replace
        path: /spec/walStorage/storageClass
        value: lvms-vg1-immediate
      - op: replace
        path: /spec/backup/volumeSnapshot/className
        value: lvms-vg1-immediate
    target:
      kind: Cluster
      name: zitadel
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: zitadel
  - patch: |-
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: zitadel-app
        namespace: zitadel
      $patch: delete
