---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-aggregated
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - probes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
