---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentelemetry-operator-controller-manager
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: manager
        minAllowed:
          cpu: 5m
          memory: 32Mi
        maxAllowed:
          cpu: 100m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
