---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-cert
  namespace: registry
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: registry
spec:
  secretName: registry-cert
  duration: 1080h # 45d
  renewBeforePercentage: 50
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  dnsNames:
    - "registry.microshift.arthurvardevanyan.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
