# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: grafana-plugins
#   namespace: grafana
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: rook-cephfs
#   volumeMode: Filesystem
# status:
#   phase: Bound
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 1Gi
