apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - clair-action/
  - gitops-ci.yaml
  - ansible-task.yaml
  - rbac.yaml
  - repo.yaml
  - certificate.yaml
  - configmap.yaml
  - push-secret.yaml
  - sa.yaml
  - namespace.yaml
  - ./limit-range.yaml
  - ./network-policy.yaml
