---
## DOCS:
## https://pipelinesascode.com/docs/guide/repositorycrd/#concurrency
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: homelab
  namespace: homelab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  url: "https://github.com/ArthurVardevanyan/HomeLab"
  concurrency_limit: 5
