---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - vpa.yaml
generatorOptions: {}
configMapGenerator:
  - files:
      - settings.yaml
    name: searxng-settings
    namespace: llm
