---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: prometheus-server
  namespace: prometheus
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
