---
apiVersion: waf.k8s.coraza.io/v1alpha1
kind: RuleSet
metadata:
  name: default-ruleset-external
  namespace: openshift-ingress
spec:
  rules:
    - name: coraza-base-rules
    # - name: coraza-sqli-rules
    # - name: coraza-xss-rules
    # - name: coraza-no-evil-monkeys
    - name: coraza-custom-rules-external
