---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: thanos-querier
  namespace: prometheus
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: thanos-querier
