# OperatorConfig defines the default settings for all CSI drivers.
---
apiVersion: csi.ceph.io/v1
kind: OperatorConfig
metadata:
  name: ceph-csi-operator-config
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  driverSpecDefaults:
    log:
      verbosity: 0
    imageSet:
      name: rook-csi-operator-image-set-configmap
    enableMetadata: true
    generateOMapInfo: false
    fsGroupPolicy: File
    deployCsiAddons: false
    clusterName: rook-ceph
    cephFsClientType: kernel
    nodePlugin:
      priorityClassName: "system-node-critical"
      kubeletDirPath: /var/lib/kubelet
      enableSeLinuxHostMount: false
      affinity:
        nodeAffinity: {}
      imagePullPolicy: IfNotPresent
      resources: {}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
    controllerPlugin:
      priorityClassName: "system-cluster-critical"
      deploymentStrategy:
        type: Recreate
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      imagePullPolicy: IfNotPresent
      replicas: 2
      resources: {}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
