---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vlinsert-ingress-logs
  namespace: openshift-ingress-logs
spec:
  namespaceSelector:
    matchNames:
      - openshift-ingress-logs
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-logs
      app.kubernetes.io/name: vlinsert
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vlselect-ingress-logs
  namespace: openshift-ingress-logs
spec:
  namespaceSelector:
    matchNames:
      - openshift-ingress-logs
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-logs
      app.kubernetes.io/name: vlselect
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vlstorage-ingress-logs
  namespace: openshift-ingress-logs
spec:
  namespaceSelector:
    matchNames:
      - openshift-ingress-logs
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-logs
      app.kubernetes.io/name: vlstorage
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
