---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vlinsert-ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vlinsert-ingress-logs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vlinsert-ingress-logs
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: vlinsert
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 25m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vlselect-ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vlselect-ingress-logs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vlselect-ingress-logs
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: vlselect
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 50m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vlstorage-ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vlstorage-ingress-logs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vlstorage-ingress-logs
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: vlstorage
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 50m
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
