---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vminsert-ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vminsert-ingress-logs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vminsert-ingress-logs
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: vminsert
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 25m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmselect-ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vmselect-ingress-logs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vmselect-ingress-logs
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: vmselect
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 100m
          memory: 3Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmstorage-ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vmstorage-ingress-logs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vmstorage-ingress-logs
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: vmstorage
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 50m
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
