---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: open-webui-dragonfly
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  skipFSGroup: true
  serviceAccountName: open-webui-dragonfly
  authentication:
    passwordFromSecret:
      name: open-webui-dragonfly-redis-url
      key: password
  # renovate: datasource=docker depName=docker.dragonflydb.io/dragonflydb/dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v2.0.0@sha256:7426fdb31ddcf7bd9499b4205f36ebaa83b26149ba1609a0d5f8f474b3631233
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/gpu: ""
  resources:
    limits:
      cpu: 75m
      memory: 320Mi
    requests:
      cpu: 15m
      memory: 64Mi
