---
apiVersion: operator.victoriametrics.com/v1
kind: VLCluster
metadata:
  name: ingress-logs
  namespace: openshift-ingress-logs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  useStrictSecurity: true
  vlinsert:
    replicaCount: 2
    extraArgs:
      http.maxGracefulShutdownDuration: "30s"
    resources:
      requests:
        cpu: "10m"
        memory: "128Mi"
      limits:
        cpu: "50m"
        memory: "384Mi"
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    podDisruptionBudget:
      minAvailable: 1
      selectorLabels:
        app.kubernetes.io/name: vlinsert
        app.kubernetes.io/instance: ingress-logs
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vlinsert
            app.kubernetes.io/instance: ingress-logs
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vlinsert
            app.kubernetes.io/instance: ingress-logs
  vlselect:
    replicaCount: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "512Mi"
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    podDisruptionBudget:
      minAvailable: 1
      selectorLabels:
        app.kubernetes.io/name: vlselect
        app.kubernetes.io/instance: ingress-logs
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vlselect
            app.kubernetes.io/instance: ingress-logs
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vlselect
            app.kubernetes.io/instance: ingress-logs
  vlstorage:
    replicaCount: 2
    retentionPeriod: "7d"
    storageDataPath: "/vl-data"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block-ci
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
    resources:
      requests:
        cpu: "10m"
        memory: "128Mi"
      limits:
        cpu: "50m"
        memory: "256Mi"
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    podDisruptionBudget:
      minAvailable: 1
      selectorLabels:
        app.kubernetes.io/name: vlstorage
        app.kubernetes.io/instance: ingress-logs
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vlstorage
            app.kubernetes.io/instance: ingress-logs
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vlstorage
            app.kubernetes.io/instance: ingress-logs
