apiVersion: v1
kind: ConfigMap
metadata:
  name: coraza-base-rules
  namespace: openshift-ingress
data:
  rules: |
    SecRuleEngine On
    SecDebugLogLevel 0
    SecRequestBodyAccess On
    SecResponseBodyAccess Off
    SecAuditLog /dev/stdout
    SecAuditLogFormat JSON
    SecAuditEngine RelevantOnly
