---
gpuAccess: plugin
prometheus:
  monitor: true
nodeSelector:
  feature.node.kubernetes.io/custom-intel.xe.gpu: "true"
tolerations:
  - key: node-role.kubernetes.io/gpu
    operator: Exists
    effect: NoSchedule
