apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./secret.yaml
components:
  - ./request-901-initialization
  - ./request-905-common-exceptions
  - ./request-911-method-enforcement
  - ./request-913-scanner-detection
  - ./request-920-protocol-enforcement
  - ./request-921-protocol-attack
  - ./request-922-multipart-attack
  - ./request-930-application-attack-lfi
  - ./request-931-application-attack-rfi
  - ./request-932-application-attack-rce
  - ./request-933-application-attack-php
  - ./request-934-application-attack-generic
  - ./request-941-application-attack-xss
  - ./request-942-application-attack-sqli
  - ./request-943-application-attack-session-fixation
  - ./request-944-application-attack-java
  - ./request-949-blocking-evaluation
  - ./response-950-data-leakages
  - ./response-951-data-leakages-sql
  - ./response-952-data-leakages-java
  - ./response-953-data-leakages-php
  - ./response-954-data-leakages-iis
  - ./response-955-web-shells
  - ./response-959-blocking-evaluation
  - ./response-980-correlation
