---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: netobserv-controller-manager
  namespace: openshift-netobserv-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netobserv-controller-manager
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: manager
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 100m
          memory: 400Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: netobserv-plugin-static
  namespace: openshift-netobserv-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netobserv-plugin-static
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: netobserv-plugin-static
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 100m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly # "RequestsAndLimits"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: netobserv-plugin
  namespace: openshift-netobserv
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netobserv-plugin
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: netobserv-plugin
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 150m
          memory: 256Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: flowlogs-pipeline
  namespace: openshift-netobserv
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: flowlogs-pipeline
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: flowlogs-pipeline
        minAllowed:
          cpu: 10m
          memory: 32Mi
        maxAllowed:
          cpu: 300m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: netobserv-ebpf-agent
  namespace: openshift-netobserv-privileged
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: netobserv-ebpf-agent
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: netobserv-ebpf-agent
        minAllowed:
          cpu: 10m
          memory: 32Mi
        maxAllowed:
          cpu: 300m
          memory: 512Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsAndLimits
