---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pr-agent-secret
  namespace: pr-agent
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: pr-agent-secret
  data:
    - secretKey: github_app
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/tekton
        property: github_app
        metadataPolicy: None
    - secretKey: github_pk
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/tekton
        property: github_pk
        metadataPolicy: None
    - secretKey: webhook_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/tekton
        property: webhook
        metadataPolicy: None
