---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - pvc.yaml
  - service-account.yaml
  - network-policy.yaml
  - vpa.yaml
