---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: llm-models
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: rook-ceph-block-ci
  volumeMode: Filesystem
