---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: llm-server
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: llm-server
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: llm
        minAllowed:
          cpu: "250m"
          memory: 8Gi
          gpu.intel.com/xe: "1"
        maxAllowed:
          cpu: "2"
          memory: 32Gi
          gpu.intel.com/xe: "1"
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
