---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: postgres-configuration
  namespace: awx
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        key: homelab/awx/postgres
        metadataPolicy: None
        property: password
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgres-configuration
    template:
      data:
        host: "awx-rw.awx.svc.cluster.local"
        port: "5432"
        database: "awx"
        username: "awx"
        type: "postgresql"
        sslmode: "prefer"
        target_session_attrs: "any"
        password: "{{ .password }}"
