---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oikb
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: oikb
    template:
      engineVersion: v2
      data:
        OPEN_WEBUI_API_KEY: "{{ .OPEN_WEBUI_API_KEY }}"
        OIKB_API_KEY: "{{ .OIKB_API_KEY }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
  data:
    - secretKey: OPEN_WEBUI_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/oikb
        property: api_key
        metadataPolicy: None
    - secretKey: OIKB_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/oikb
        property: daemon_key
        metadataPolicy: None
    - secretKey: GITHUB_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/github/read-only
        property: token
        metadataPolicy: None
