---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oikb
  namespace: llm
  labels:
    app.kubernetes.io/name: oikb
    app.kubernetes.io/instance: oikb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oikb
  endpoints:
    - port: http
      path: /metrics
