---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-storage
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block-ci
  volumeMode: Filesystem
