---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./cronjob.yaml
  - ./external-secret.yaml
  - ./network-policy.yaml
  - ./rbac.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - unas.sh
    name: unas
    namespace: immich
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "4"
