---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - egress-firewall.yaml
components:
  - ../../components/llama-cpp
  - ../../components/open-webui
  - ../../components/cnpg-open-webui
  - ../../components/dragonfly-open-webui
  - ../../components/open-webui-gateway
  - ../../components/searxng
