---
apiVersion: waf.k8s.coraza.io/v1alpha1
kind: Engine
metadata:
  name: coraza-internal
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ruleSet:
    name: internal-ruleset
  failurePolicy: fail
  driver:
    istio:
      wasm:
        image: "oci://ghcr.io/networking-incubator/coraza-proxy-wasm:1902646ac7391b65be092cdec9b47d29fa5724c7 "
        mode: gateway
        workloadSelector:
          matchLabels:
            coraza: internal-ruleset
        ruleSetCacheServer:
          pollIntervalSeconds: 5
