---
apiVersion: v1
kind: Secret
metadata:
  name: pgdump-config
  namespace: cnpg-system
  labels:
    name: pgdump-config
    app.kubernetes.io/instance: cloudnative-pg
stringData:
  config.json: |
    {
      "version": "10",
      "aliases": {
        "truenas": {
          "url": "https://s3.unas.arthurvardevanyan.com",
          "accessKey": "<path:secret/data/homelab/minio#access_key>",
          "secretKey": "<path:secret/data/homelab/minio#access_key>",
          "api": "s3v4",
          "path": "auto"
        }
      }
    }
  pgdump.sh: |-
    #!/bin/sh

    LOCATION=/mnt/db-dump/pg_dump
    mkdir ${LOCATION}

    dump_db() {
      _NAME="$1"
      _URI="$2"
      _FILE="$3"
      {
        echo "Dumping ${_NAME}"
        _START=$(date +%s)
        pg_dump -d "${_URI}" > "${LOCATION}/${_FILE}.sql"
        pg_dump -Fc -d "${_URI}" -f "${LOCATION}/${_FILE}.db"
        echo "${_NAME} dump completed in $(($(date +%s) - _START))s"
      } &
    }

    # dump_db "AWX"             "<path:secret/data/homelab/awx/postgres#db_uri>"      "awx"
    # dump_db "Clair"           "<path:secret/data/homelab/postgres#clair_uri>"       "clair"
    # dump_db "Finance Tracker" "<path:secret/data/finance-tracker/database/#uri>"    "finance-tracker"
    # dump_db "Gitea"           "<path:secret/data/homelab/gitea/postgres/#uri>"      "gitea"
    dump_db   "Grafana"         "<path:secret/data/homelab/grafana/postgres/#uri>"    "grafana"
    # dump_db "Homeassistant"   "<path:secret/data/homelab/homeassistant/#uri>"       "homeassistant"
    dump_db   "Immich"          "<path:secret/data/homelab/immich/#db_url>"           "immich"
    dump_db   "NetBox"          "<path:secret/data/homelab/netbox#db_uri>"            "netbox"
    # dump_db "Nextcloud FPM"   "<path:secret/data/homelab/nextcloud/fpm/#db_uri>"    "nextcloud-fpm"
    dump_db   "Quay"            "<path:secret/data/homelab/postgres#quay_uri>"        "quay"
    # dump_db "Spotify"         "<path:secret/data/spotify/database/#uri>"            "spotify"
    dump_db   "Stackrox"        "<path:secret/data/homelab/stackrox/postgres#uri>"    "stackrox"

    wait

    find ${LOCATION} -maxdepth 1 -type f -empty -delete

    mkdir  /tmp/.mc
    cp /mnt/pg_dump/config.json /tmp/.mc/config.json
    mc cp ${LOCATION}/* truenas/db-dump
type: Opaque
