---
apiVersion: v1
kind: Secret
metadata:
  name: pgdump-config
  namespace: cnpg-system
  labels:
    name: pgdump-config
    app.kubernetes.io/instance: cloudnative-pg
stringData:
  config.json: |
    {
      "version": "10",
      "aliases": {
        "truenas": {
          "url": "https://s3.unas.arthurvardevanyan.com",
          "accessKey": "<path:secret/data/homelab/minio#access_key>",
          "secretKey": "<path:secret/data/homelab/minio#access_key>",
          "api": "s3v4",
          "path": "auto"
        }
      }
    }
  pgdump.sh: |-
    #!/bin/sh

    LOCATION=/mnt/db-dump/pg_dump
    mkdir ${LOCATION}

    # echo "Dumping Finance Tracker"
    # pg_dump -d <path:secret/data/finance-tracker/database/#uri> > ${LOCATION}/finance-tracker.sql
    # pg_dump -Fc -d <path:secret/data/finance-tracker/database/#uri> -f ${LOCATION}/finance-tracker.db
    # echo "Dumping Spotify"
    # pg_dump -d <path:secret/data/spotify/database/#uri> > ${LOCATION}/spotify.sql
    # pg_dump -Fc -d <path:secret/data/spotify/database/#uri> -f ${LOCATION}/spotify.db
    # echo "Dumping Gitea"
    # pg_dump -d <path:secret/data/homelab/gitea/postgres/#uri> > ${LOCATION}/gitea.sql
    # pg_dump -Fc -d <path:secret/data/homelab/gitea/postgres/#uri> -f ${LOCATION}/gitea.db
    # echo "Dumping Homeassistant"
    # pg_dump -d <path:secret/data/homelab/homeassistant/#uri> > ${LOCATION}/homeassistant.sql
    # pg_dump -Fc -d <path:secret/data/homelab/homeassistant/#uri> -f ${LOCATION}/homeassistant.db
    echo "Dumping Grafana"
    pg_dump -d <path:secret/data/homelab/grafana/postgres/#uri> > ${LOCATION}/grafana.sql
    pg_dump -Fc -d <path:secret/data/homelab/grafana/postgres/#uri> -f ${LOCATION}/grafana.db
    # echo "Dumping immich"
    # pg_dump -d <path:secret/data/homelab/immich/#db_url> > ${LOCATION}/immich.sql
    # pg_dump -Fc -d <path:secret/data/homelab/immich/#db_url> -f ${LOCATION}/immich.db
    # echo "Dumping Nextcloud FPM"
    # pg_dump -d <path:secret/data/homelab/nextcloud/fpm/#db_uri> > ${LOCATION}/nextcloud-fpm.sql
    # pg_dump -Fc -d <path:secret/data/homelab/nextcloud/fpm/#db_uri> -f ${LOCATION}/nextcloud-fpm.db
    # echo "Dumping Quay"
    # pg_dump -d  <path:secret/data/homelab/postgres#quay_uri>  > ${LOCATION}/quay.sql
    # pg_dump -Fc -d  <path:secret/data/homelab/postgres#quay_uri>  -f ${LOCATION}/quay.db
    #echo "Dumping Clair"
    #pg_dump -d  <path:secret/data/homelab/postgres#clair_uri>  > ${LOCATION}/clair.sql
    #pg_dump -Fc -d  <path:secret/data/homelab/postgres#clair_uri>  -f ${LOCATION}/clair.db
    # echo "Dumping Stackrox"
    # pg_dump -d  <path:secret/data/homelab/stackrox/postgres#uri>  > ${LOCATION}/stackrox.sql
    # pg_dump -Fc -d  <path:secret/data/homelab/stackrox/postgres#uri>  -f ${LOCATION}/stackrox.db
    # echo "Dumping NetBox"
    # pg_dump -d  <path:secret/data/homelab/netbox#db_uri>  > ${LOCATION}/netbox.sql
    # pg_dump -Fc -d  <path:secret/data/homelab/netbox#db_uri>  -f ${LOCATION}/netbox.db
    # echo "Dumping AWX"
    # pg_dump -d  <path:secret/data/homelab/awx/postgres#db_uri>  > ${LOCATION}/awx.sql
    # pg_dump -Fc -d  <path:secret/data/homelab/awx/postgres#db_uri>  -f ${LOCATION}/awx.db

    mkdir  /tmp/.mc
    cp /mnt/pg_dump/config.json /tmp/.mc/config.json
    mc cp ${LOCATION}/* truenas/db-dump
type: Opaque
