---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
resources:
  - namespace.yaml
  - argocd.yaml
  - cmp-plugin.yaml
  - creds.yaml
  - cronjob.yaml
  - egress-firewall.yaml
  - k3s-cluster.yaml
  - limit-range.yaml
  - network-policy.yaml
  - notificationsConfiguration.yaml
  - rbac.yaml
  - repository.yaml
  - rules.yaml
  - secret.yaml
  - service-monitor.yaml
  - vpa.yaml
components:
  - ./dragonfly
  - ./gateway
  - ./microshift
  - ./notifications
