---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - limit-range.yaml
  - argocd-operator-namespace.yaml
  - argocd-operator-operatorgroup.yaml
  - subscription.yaml
  - service-monitor.yaml
  - rules.yaml
  - network-policy.yaml
  - rbac.yaml
  - cmp-plugin.yaml
  - argocd.yaml
  - installplan-approver.yaml
  - gitopsservice.yaml
  - openshift-gitops/namespace.yaml
  - openshift-gitops/vpa.yaml
  - openshift-gitops/pdb.yaml
  - openshift-gitops/hpa.yaml
  - notifications/notificationsConfiguration.yaml
  - notifications/secret.yaml
  - notifications/network-policy.yaml
  - dragonfly/dragonfly.yaml
  - dragonfly/network-policy.yaml
  - k3s-cluster.yaml
  - ./egress-firewall.yaml
  - ./secret.yaml
  - ./repository.yaml
  - ./vpa.yaml
components:
  - ./microshift
