---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: argocd-server
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: argocd-repo-server
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-application-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: argocd-application-controller
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-notifications-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app: argocd-notifications-controller
