---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
