---
apiVersion: kustomize.config.k8s.io/v1beta1
kind:
  Kustomization
  # - ./service.yaml
resources:
  - ./dns.yaml
  - ./http-route.yaml
  - ./certificate.yaml
  - ./probe.yaml
  - ../../base
  - ./vpa.yaml
components:
  - ../../components/technitium-dns
  - ../../components/openshift
