---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.101.10.245"
  name: technitium-dns-udp-bgp
  namespace: technitium-dns
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: https
      port: 53443
      protocol: TCP
      targetPort: 53443
  selector:
    app: technitium-dns
  type: LoadBalancer
  loadBalancerClass: metallb.io/metallb-class
