---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  namespace: blackbox-exporter
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: ip4
      http_2xx_insecure:
        prober: http
        http:
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
