---
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: network-observability
spec:
  networkPolicy:
    enable: true
    additionalNamespaces:
      - openshift-netobserv-loki
  agent:
    ebpf:
      cacheActiveTimeout: 15s
      cacheMaxFlows: 120000
      excludeInterfaces:
        - lo
      imagePullPolicy: IfNotPresent
      kafkaBatchSize: 1048576
      logLevel: info
      metrics:
        server:
          tls:
            insecureSkipVerify: true
            type: Auto
      resources:
        limits:
          cpu: 45m
          memory: 256Mi
        requests:
          cpu: 15m
          memory: 128Mi
      sampling: 75 #50 # 35 # 5 # 0 # Send All Flows, 50 Default
      privileged: true
      features:
        - PacketDrop
        - DNSTracking
        - FlowRTT
        - NetworkEvents
        - PacketTranslation
        # - EbpfManager
        - UDNMapping
        # - IPSec
    ipfix:
      cacheActiveTimeout: 20s
      cacheMaxFlows: 400
      clusterNetworkOperator:
        namespace: openshift-network-operator
      forceSampleAll: false
      ovnKubernetes:
        containerName: ovnkube-node
        daemonSetName: ovnkube-node
        namespace: ovn-kubernetes
      sampling: 400
    type: eBPF
  consolePlugin:
    autoscaler:
      maxReplicas: 2
      status: Disabled
    enable: true
    imagePullPolicy: IfNotPresent
    logLevel: info
    portNaming:
      enable: true
    quickFilters:
      - default: true
        filter:
          flow_layer: '"app"'
        name: Applications
      - filter:
          flow_layer: '"infra"'
        name: Infrastructure
      - default: true
        filter:
          dst_kind: '"Pod"'
          src_kind: '"Pod"'
        name: Pods network
      - filter:
          dst_kind: '"Service"'
        name: Services network
      - filter:
          src_subnet_label: '"",EXT:'
        name: External ingress
      - filter:
          dst_subnet_label: '"",EXT:'
        name: External egress
    replicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 32Mi
  deploymentModel: Service
  kafka:
    address: ""
    sasl:
      type: Disabled
    topic: ""
  loki:
    enable: false # true
    mode: LokiStack
    lokiStack:
      name: loki-netobserv
      namespace: openshift-netobserv-loki
    readTimeout: 30s
    writeBatchSize: 102760448
    writeBatchWait: 15s
    writeTimeout: 30s
  namespace: openshift-netobserv
  processor:
    clusterName: ""
    addZone: true
    advanced:
      scheduling:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app: flowlogs-pipeline
              - weight: 50
                podAffinityTerm:
                  topologyKey: topology.kubernetes.io/zone
                  labelSelector:
                    matchLabels:
                      app: flowlogs-pipeline
    imagePullPolicy: IfNotPresent
    kafkaConsumerAutoscaler:
      maxReplicas: 2
      status: Disabled
    subnetLabels: {}
    kafkaConsumerBatchSize: 10485760
    kafkaConsumerQueueCapacity: 1000
    kafkaConsumerReplicas: 2
    unmanagedReplicas: true
    logLevel: info
    logTypes: Flows
    metrics:
      server:
        port: 9102
        tls:
          type: Disabled
    multiClusterDeployment: false
    slicesConfig:
      collectionMode: AlwaysCollect
      enable: false
    resources:
      limits:
        cpu: 300m
        memory: 384Mi
      requests:
        cpu: 100m
        memory: 256Mi
