---
# https://github.com/netobserv/netobserv-operator/issues/2889
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.22/html/network_observability/configuring-network-observability-operators#network-observability-grant-permissions-custom-namespace-and-secret-access_network_observability
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.22/html/network_observability/network-observability-operator-release-notes#network-observability-operator-release-notes-1-12-2-fixed-issues_network-observability-operator-release-notes
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netobserv-informers-flp-custom
subjects:
  - kind: ServiceAccount
    name: flowlogs-pipeline
    namespace: openshift-netobserv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-informers
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netobserv-hostnetwork-flp-custom
subjects:
  - kind: ServiceAccount
    name: flowlogs-pipeline
    namespace: openshift-netobserv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-hostnetwork
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netobserv-lokiwriter-flp-transformer-custom
subjects:
  - kind: ServiceAccount
    name: flowlogs-pipeline
    namespace: openshift-netobserv
  - kind: ServiceAccount
    name: flowlogs-pipeline-transformer
    namespace: openshift-netobserv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-loki-writer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netobserv-tokenreview-plugin-custom
subjects:
  - kind: ServiceAccount
    name: netobserv-plugin
    namespace: openshift-netobserv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-token-review
