---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-resource-limits
  namespace: openshift-netobserv-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  background: false
  rules:
    - name: netobserv-plugin-static
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Deployment
              selector:
                matchLabels:
                  app: netobserv-plugin-static
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                containers:
                  - (name): netobserv-plugin-static
                    resources:
                      limits:
                        cpu: 100m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 32Mi
