---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - installplan-approver.yaml
  - olsconfig.yaml
  - alerts-adapter-config.yaml
  - external-secret-llm.yaml
  - vpa/
