---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: argocd-dragonfly
  namespace: argocd-apps
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 2
  skipFSGroup: true
  # renovate: datasource=docker depName=docker.dragonflydb.io/dragonflydb/dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.2@sha256:e45de310788d110d621655f6340b5b0818d860210ad6a350a4d277d57c14349a
  resources:
    limits:
      cpu: 50m
      memory: 320Mi
    requests:
      cpu: 10m
      memory: 64Mi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: dragonfly
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
  # snapshot:
  #   cron: "*/5 * * * *"
  #   persistentVolumeClaimSpec:
  #     storageClassName: rook-ceph-block

  #     accessModes:
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 1Gi
