---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: open-webui-data
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 5Gi
