---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-config
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: open-webui-config
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/open-webui
        property: webui_secret_key
        metadataPolicy: None
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/open-webui/zitadel
        property: client_id
        metadataPolicy: None
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/llm/open-webui/zitadel
        property: client_secret
        metadataPolicy: None
