---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: gpu
  name: 99-collector-inotify-fix
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: sysctl-collector-inotify-fix.service
          enabled: true
          contents: |
            [Unit]
            Description=Set fs.inotify.max_user_watches for vector collector
            Before=final.target
            [Service]
            Type=oneshot
            ExecStart=/usr/sbin/sysctl -w fs.inotify.max_user_watches=524288
            RemainAfterExit=yes
            [Install]
            WantedBy=multi-user.target
