---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: litellm-dragonfly
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  skipFSGroup: true
  serviceAccountName: litellm-dragonfly
  authentication:
    passwordFromSecret:
      name: litellm-dragonfly-redis-url
      key: password
  # renovate: datasource=docker depName=docker.dragonflydb.io/dragonflydb/dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.40.1@sha256:ebf3c6c213e82fb51b4521660cca13f06f3421dc5b1ed14f2f474c50b5e29986
  tolerations:
    - key: node-role.kubernetes.io/gpu
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/gpu: ""
  resources:
    limits:
      cpu: 150m
      memory: 1Gi
    requests:
      cpu: 15m
      memory: 64Mi
