---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./pvc.yaml
images:
  - name: registry.arthurvardevanyan.com/homelab/minio
    newName: registry.microshift.arthurvardevanyan.com/homelab/minio
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1Gi
    target:
      kind: Deployment
      name: minio
