apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: loki-external
  namespace: openshift-ingress
spec:
  hosts:
    - vminsert-ingress-logs.openshift-ingress-logs.svc.cluster.local.
  ports:
    - number: 8480
      name: http
      protocol: HTTP
  resolution: DNS
  location: MESH_INTERNAL
