---
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  labels:
    app.kubernetes.io/instance: okd-configuration
spec:
  channel: stable-scos-4 # next-scos-4
  clusterID: <path:secret/data/okd#cluster_id>
  desiredUpdate:
    force: false
    image: quay.io/okd/scos-release@sha256:f82cfb607a7b66a295f5b727bc53607dc65f8608a6165283b6eedc2435c718fb
    version: 4.22.0-okd-scos.6
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
