---
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  labels:
    app.kubernetes.io/instance: okd-configuration
spec:
  channel: next-scos-4 #stable-scos
  clusterID: <path:secret/data/okd#cluster_id>
  desiredUpdate:
    force: false
    image: quay.io/okd/scos-release@sha256:5856c793b1925a84077c85729dfc522dab3877158df6e90bcac9359232e8cc1d
    version: 4.22.0-okd-scos.ec.9
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
