---
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  labels:
    app.kubernetes.io/instance: okd-configuration
spec:
  channel: stable-scos-4 # next-scos-4
  clusterID: <path:secret/data/okd#cluster_id>
  desiredUpdate:
    force: false
    image: quay.io/okd/scos-release@sha256:790386476b24e1a1043aa865c98d2bfeebdd467aa54859f0f53ecd6c487a8036
    version: 4.22.0-okd-scos.7
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
