---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone
  namespace: media-ingest
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rclone
  data:
    - secretKey: rclone.conf
      remoteRef: # checkov:skip=CKV_SECRET_6 Placeholder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: homelab/media-ingest
        property: unas
        metadataPolicy: None
