---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coraza-custom-default
  namespace: openshift-ingress
data:
  rules: |
    # Include @recommended-conf
    # Include @demo-conf
    SecDebugLogLevel 0
    SecRuleEngine On
    # Include @crs-setup-conf
    # Include @owasp_crs/*.conf
