---
# renovate: datasource=docker depName=ghcr.io/intel/xpumanager/xpumd
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xpumd
  namespace: intel-device-plugins-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    helm.sh/chart: xpumd-2.0.1
    app.kubernetes.io/name: xpumd
    app.kubernetes.io/instance: xpumd
    app.kubernetes.io/version: "v2.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xpumd
      app.kubernetes.io/instance: xpumd
  template:
    metadata:
      annotations:
        checksum/config: ef5ad6b578028c9cc86e2af849e64271225cead2987520f38416b1f01a95dc01
        checkov.io/skip: CKV_K8S_21=SYS_ADMIN needed for engine utilization metrics
      labels:
        app.kubernetes.io/name: xpumd
        app.kubernetes.io/instance: xpumd
    spec:
      serviceAccountName: xpumd
      resourceClaims:
        - name: xpumd
          resourceClaimTemplateName: xpumd
      automountServiceAccountToken: false
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      dnsPolicy: ClusterFirst
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: false
      containers:
        - name: xpumd
          # renovate: datasource=docker depName=ghcr.io/intel/xpumanager/xpumd
          image: "ghcr.io/intel/xpumanager/xpumd@sha256:61990529b71a461ea6607108c86a5c71aaab0677264d5ea91211d5dcd19d1dff"
          imagePullPolicy: Always
          args:
            - "--config=/etc/xpumd/config-receiver-crashlog.yaml"
            - "--config=/etc/xpumd/config-processor-xpustatus.yaml"
            - "--config=/etc/xpumd/config-exporter-xpuinfo.yaml"
            - "--config=/etc/xpumd/config.yaml"
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
            # Required for GPU device access, unless container runtime allows device file owner override:
            # - https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/
            # Required also for all other metrics than frequency, memory usage, power
            runAsUser: 0
            capabilities:
              drop:
                - ALL
              add:
                # required for engine utilization
                # (bug in underlying layers, PERFMON should be enough)
                - SYS_ADMIN
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            # map all GPUs to container
            claims:
              - name: xpumd
            limits:
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /etc/xpumd
              readOnly: true
            - name: rundir
              mountPath: /run/xpumd
            - name: crashlog
              mountPath: /var/log/crashlog
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: xpumd-config
        - name: rundir
          hostPath:
            path: /run/xpumd
            type: DirectoryOrCreate
        - name: crashlog
          hostPath:
            path: /var/log/crashlog
            type: DirectoryOrCreate
