---
apiVersion: v1
kind: Service
metadata:
  name: xpumd
  namespace: intel-device-plugins-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: xpumd
    app.kubernetes.io/instance: xpumd
spec:
  selector:
    app.kubernetes.io/name: xpumd
    app.kubernetes.io/instance: xpumd
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None
