---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xpumd
  namespace: intel-device-plugins-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    helm.sh/chart: xpumd-2.0.1
    app.kubernetes.io/name: xpumd
    app.kubernetes.io/instance: xpumd
    app.kubernetes.io/version: "v2.0.1"
    app.kubernetes.io/managed-by: Helm
