---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: netbox-dragonfly
  namespace: netbox
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 2
  skipFSGroup: true
  # renovate: datasource=docker depName=docker.dragonflydb.io/dragonflydb/dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.40.1@sha256:ebf3c6c213e82fb51b4521660cca13f06f3421dc5b1ed14f2f474c50b5e29986
  resources:
    limits:
      cpu: 75m
      memory: 320Mi
    requests:
      cpu: 20m
      memory: 64Mi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: dragonfly
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
  # snapshot:
  #   cron: "*/5 * * * *"
  #   persistentVolumeClaimSpec:
  #     storageClassName: rook-ceph-block

  #     accessModes:
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 1Gi
