---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-apps-server
  namespace: argocd-apps
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-apps-server
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-apps-repo-server
  namespace: argocd-apps
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-apps-repo-server
