---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arthurvardevanyan-com-cert
  namespace: openshift-ingress
spec:
  secretName: arthurvardevanyan-com-cert
  duration: 1080h # 45d
  renewBeforePercentage: 50
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
  dnsNames:
    - "www.arthurvardevanyan.com"
    - "arthurvardevanyan.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spotify-cert
  namespace: openshift-ingress
spec:
  secretName: spotify-cert
  duration: 1080h # 45d
  renewBeforePercentage: 50
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
  dnsNames:
    - "analytics-for-spotify.arthurvardevanyan.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
