---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./certificate.yaml
  - ./gateway.yaml
  - ./hpa.yaml
  - ./loadbalancer.yaml
  - ./pdb.yaml
  - ./authorization-policy.yaml
  - ./network-policy.yaml
  - ./kyverno.yaml
  - ./coraza/configmap.yaml
  - ./coraza/engine.yaml
  - ./coraza/ruleset.yaml
  - ./wiretap/wasm-plugin.yaml
