---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Commented out (not needed/working):
# - pihole.yaml
resources:
  - cert-manager.yaml
  - cloudflare-ddns.yaml
  - external-secrets-operator.yaml
  - kfca.yaml
  - kube-eagle.yaml
  - kube-vip.yaml
  - kyverno.yaml
  - metrics-server.yaml
  - minio-unas.yaml
  - minio.yaml
  - nmstate.yaml
  - node-exporter.yaml
  - ntp.yaml
  - okd-configuration.yaml
  - olm.yaml
  - registry.yaml
  - stackrox-secure.yaml
  - technitium-dns.yaml
  - uptime-kuma.yaml
