---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
